### ISSUE TITLE
【CIM3.4】DBアップデート時の注意点（max_connections）

### ISSUE THREAD

**Issue by ookanobu** [exgennetworks/CIM_Manual#1]
旧来の Redmine はやめて issue でタスク管理をしてみる
http://trac.exgen.co.jp/redmine/issues/15187

以下の注意書きをインストールマニュアルへ記載する。

DB アップデート時に CIM がすべての DB に対して接続をおこなうため、DB の数が Postgresql の max_connections の値よりも上回っている場合、
DB アップデートに失敗します。

※エラー内容の例

> exgen01(exgen01):Database error:FATAL:  現在クライアント数が多すぎます
exgen02(exgen02):Database error:FATAL:  現在クライアント数が多すぎます
exgen03(exgen03):Database error:FATAL:  現在クライアント数が多すぎます
exgen04(exgen04):Database error:FATAL:  現在クライアント数が多すぎます

**Comment by ookatom** [comment]
修正したので確認のプルリク送るぞコラ

**Comment by ookanobu** [comment]
#4 プルリク送ったぞコラ

**Comment by ookatom** [comment]
マージ完了。PDF化よろ

**Comment by ookanobu** [comment]
PDF 化してプルリク送るぞコラ

**Comment by ookanobu** [comment]
プルリク承認したけど、issue とプルリク両方でやるのシンドイわ。。。

**Comment by ookanobu** [comment]
もうリリースして

**Comment by ookatom** [comment]
よっしゃクローズにするで！
